# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dementia.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1856, 970)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Greenframebehind = QtWidgets.QFrame(self.centralwidget)
        self.Greenframebehind.setGeometry(QtCore.QRect(10, 4, 1841, 941))
        self.Greenframebehind.setStyleSheet("background-color: rgb(16, 79, 127);")
        self.Greenframebehind.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Greenframebehind.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Greenframebehind.setObjectName("Greenframebehind")
        self.frameBehindplotWidget = QtWidgets.QFrame(self.Greenframebehind)
        self.frameBehindplotWidget.setGeometry(QtCore.QRect(9, 3, 1822, 911))
        self.frameBehindplotWidget.setStyleSheet("\n"
"background-color: rgb(199, 240, 248);")
        self.frameBehindplotWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBehindplotWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBehindplotWidget.setObjectName("frameBehindplotWidget")
        self.TitleLabel = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.TitleLabel.setGeometry(QtCore.QRect(816, 20, 391, 41))
        self.TitleLabel.setStyleSheet("\n"
"font: 700 11pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(58, 115, 173);\n"
"border radius: 12px;")
        self.TitleLabel.setObjectName("TitleLabel")
        self.plotWidget = QtWidgets.QWidget(self.frameBehindplotWidget)
        self.plotWidget.setGeometry(QtCore.QRect(210, 191, 1591, 501))
        self.plotWidget.setStyleSheet("\n"
"\n"
"QWidget#plotWidget{border-radius: 6px;\n"
"    background-color: rgb(247, 255, 251);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 10pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QWidget:hover#plotWidget\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.plotWidget.setObjectName("plotWidget")
        self.tableWidget = QtWidgets.QTableWidget(self.plotWidget)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1591, 611))
        self.tableWidget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.behindTitleLabel1_2 = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.behindTitleLabel1_2.setGeometry(QtCore.QRect(800, 10, 421, 61))
        self.behindTitleLabel1_2.setStyleSheet("\n"
"font: 700 11pt \"Segoe UI\";\n"
"background-color: rgb(16, 79, 127);\n"
"border radius: 12px;")
        self.behindTitleLabel1_2.setText("")
        self.behindTitleLabel1_2.setObjectName("behindTitleLabel1_2")
        self.uploadcsvButton = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.uploadcsvButton.setGeometry(QtCore.QRect(10, 40, 171, 41))
        self.uploadcsvButton.setStyleSheet("\n"
"\n"
"QPushButton#uploadcsvButton{border-radius: 12px;\n"
"    background-color: rgb(247, 255, 251);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 10pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#uploadcsvButton\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/imagesicons/addIcon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.uploadcsvButton.setIcon(icon)
        self.uploadcsvButton.setObjectName("uploadcsvButton")
        self.frameBehindplotWidget2 = QtWidgets.QFrame(self.frameBehindplotWidget)
        self.frameBehindplotWidget2.setGeometry(QtCore.QRect(200, 180, 1611, 621))
        self.frameBehindplotWidget2.setStyleSheet("QFrame#frameBehindplotWidget2{border-radius: 6px;\n"
"    background-color: rgb(16, 79, 127);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 10pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QFrame:hover#frameBehindplotWidget2\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.frameBehindplotWidget2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameBehindplotWidget2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBehindplotWidget2.setObjectName("frameBehindplotWidget2")
        self.NumberofPatients = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.NumberofPatients.setGeometry(QtCore.QRect(220, 90, 181, 31))
        self.NumberofPatients.setStyleSheet("\n"
"\n"
"QPushButton#NumberofPatients{border-radius: 12px;\n"
"    background-color: rgb(155, 232, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#NumberofPatients\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.NumberofPatients.setObjectName("NumberofPatients")
        self.correlationMatrixbutton = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.correlationMatrixbutton.setGeometry(QtCore.QRect(410, 90, 181, 31))
        self.correlationMatrixbutton.setStyleSheet("\n"
"\n"
"QPushButton#correlationMatrixbutton{border-radius: 12px;\n"
"    \n"
"    border-color: rgb(85, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#correlationMatrixbutton\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.correlationMatrixbutton.setObjectName("correlationMatrixbutton")
        self.viewAgeplot = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.viewAgeplot.setGeometry(QtCore.QRect(600, 90, 191, 31))
        self.viewAgeplot.setStyleSheet("\n"
"\n"
"QPushButton#viewAgeplot{border-radius: 12px;\n"
"    background-color: rgb(62, 197, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#viewAgeplot\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.viewAgeplot.setObjectName("viewAgeplot")
        self.plotMMSE = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.plotMMSE.setGeometry(QtCore.QRect(410, 130, 171, 31))
        self.plotMMSE.setStyleSheet("\n"
"\n"
"QPushButton#plotMMSE{border-radius: 12px;\n"
"    font: 700 9pt \"Segoe UI\";\n"
"    background-color: rgb(0, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#plotMMSE\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.plotMMSE.setObjectName("plotMMSE")
        self.viewGroupPlot = QtWidgets.QComboBox(self.frameBehindplotWidget)
        self.viewGroupPlot.setGeometry(QtCore.QRect(600, 130, 191, 31))
        self.viewGroupPlot.setStyleSheet("\n"
"\n"
"QComboBox#viewGroupPlot{border-radius: 12px;\n"
"    \n"
"    border-color: rgb(85, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"    background-color: rgb(158, 213, 255);\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QComboBox:hover#viewGroupPlot\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.viewGroupPlot.setObjectName("viewGroupPlot")
        self.viewGroupPlot.addItem("")
        self.textEdit = QtWidgets.QTextEdit(self.frameBehindplotWidget)
        self.textEdit.setGeometry(QtCore.QRect(200, 820, 1611, 81))
        self.textEdit.setStyleSheet("background-color: rgb(0, 59, 177);\n"
"")
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.label.setGeometry(QtCore.QRect(210, 825, 1591, 71))
        self.label.setStyleSheet("background-color: rgb(222, 241, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.comparisonresultButton = QtWidgets.QPushButton(self.frameBehindplotWidget)
        self.comparisonresultButton.setGeometry(QtCore.QRect(1240, 130, 371, 31))
        self.comparisonresultButton.setStyleSheet("\n"
"\n"
"QPushButton#comparisonresultButton{border-radius: 12px;\n"
"    \n"
"    border-color: rgb(85, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QPushButton:hover#comparisonresultButton\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.comparisonresultButton.setObjectName("comparisonresultButton")
        self.preprocessingFrame = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.preprocessingFrame.setGeometry(QtCore.QRect(210, 80, 601, 91))
        self.preprocessingFrame.setStyleSheet("\n"
"\n"
"QLabel#preprocessingLabel{border-radius: 12px;\n"
"    background-color: rgb(247, 255, 251);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"\n"
"    font: 10pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QLabel:hover#preprocessingLabel\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.preprocessingFrame.setMidLineWidth(-1)
        self.preprocessingFrame.setText("")
        self.preprocessingFrame.setObjectName("preprocessingFrame")
        self.dataprocessingLabel = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.dataprocessingLabel.setGeometry(QtCore.QRect(430, 56, 181, 21))
        self.dataprocessingLabel.setStyleSheet("font: 9pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"font: 700 9pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"border radius: 12px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 127);")
        self.dataprocessingLabel.setObjectName("dataprocessingLabel")
        self.viewGroupPlot_2 = QtWidgets.QComboBox(self.frameBehindplotWidget)
        self.viewGroupPlot_2.setGeometry(QtCore.QRect(220, 130, 181, 31))
        self.viewGroupPlot_2.setStyleSheet("\n"
"\n"
"QComboBox#viewGroupPlot_2{border-radius: 12px;\n"
"    \n"
"    border-color: rgb(85, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"    background-color: rgb(158, 213, 255);\n"
"border-color:rgb(16, 79, 127);\n"
"    font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QComboBox:hover#viewGroupPlot_2\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.viewGroupPlot_2.setObjectName("viewGroupPlot_2")
        self.viewGroupPlot_2.addItem("")
        self.machineLearningcomboBox = QtWidgets.QComboBox(self.frameBehindplotWidget)
        self.machineLearningcomboBox.setGeometry(QtCore.QRect(1240, 90, 371, 31))
        self.machineLearningcomboBox.setStyleSheet("\n"
"\n"
"QComboBox#machineLearningcomboBox{border-radius: 12px;\n"
"    \n"
"    border-color: rgb(85, 170, 255);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"    background-color: rgb(158, 213, 255);\n"
"border-color:rgb(16, 79, 127);\n"
"        font: 700 9pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QComboBox:hover#machineLearningcomboBox\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.machineLearningcomboBox.setObjectName("machineLearningcomboBox")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningcomboBox.addItem("")
        self.machineLearningFrame = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.machineLearningFrame.setGeometry(QtCore.QRect(1210, 80, 601, 91))
        self.machineLearningFrame.setStyleSheet("\n"
"\n"
"QLabel#machineLearningLabel{border-radius: 12px;\n"
"    background-color: rgb(247, 255, 251);\n"
"border-style:outset;\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"\n"
"    font: 10pt \"Segoe UI\";\n"
";}\n"
"\n"
"\n"
"QLabel:hover#machineLearningLabel\n"
"{\n"
"border-width:2px;\n"
"    border-color: rgb(84, 204, 255);\n"
"}\n"
"")
        self.machineLearningFrame.setMidLineWidth(-1)
        self.machineLearningFrame.setText("")
        self.machineLearningFrame.setObjectName("machineLearningFrame")
        self.machinelearningLabel = QtWidgets.QLabel(self.frameBehindplotWidget)
        self.machinelearningLabel.setGeometry(QtCore.QRect(1430, 56, 191, 21))
        self.machinelearningLabel.setStyleSheet("font: 9pt \"Segoe UI\";\n"
"text-decoration: underline;\n"
"font: 700 9pt \"Segoe UI\";\n"
"color: rgb(0, 0, 0);\n"
"border radius: 12px;\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 127);")
        self.machinelearningLabel.setObjectName("machinelearningLabel")
        self.machineLearningFrame.raise_()
        self.preprocessingFrame.raise_()
        self.frameBehindplotWidget2.raise_()
        self.behindTitleLabel1_2.raise_()
        self.TitleLabel.raise_()
        self.plotWidget.raise_()
        self.uploadcsvButton.raise_()
        self.NumberofPatients.raise_()
        self.correlationMatrixbutton.raise_()
        self.viewAgeplot.raise_()
        self.plotMMSE.raise_()
        self.viewGroupPlot.raise_()
        self.textEdit.raise_()
        self.label.raise_()
        self.comparisonresultButton.raise_()
        self.dataprocessingLabel.raise_()
        self.viewGroupPlot_2.raise_()
        self.machineLearningcomboBox.raise_()
        self.machinelearningLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1856, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "       Dementia Exploratory Data Analysis"))
        self.uploadcsvButton.setText(_translate("MainWindow", "Upload csv"))
        self.NumberofPatients.setText(_translate("MainWindow", "Number of patients"))
        self.correlationMatrixbutton.setText(_translate("MainWindow", "Correlation matrix"))
        self.viewAgeplot.setText(_translate("MainWindow", "View Age plot"))
        self.plotMMSE.setText(_translate("MainWindow", "Plot MMSE"))
        self.viewGroupPlot.setCurrentText(_translate("MainWindow", "   View Group plot"))
        self.viewGroupPlot.setItemText(0, _translate("MainWindow", "   View Group plot"))
        self.comparisonresultButton.setText(_translate("MainWindow", "Comparison Result (Machine Learning used)"))
        self.dataprocessingLabel.setText(_translate("MainWindow", "       DATA PREPROCESSING           "))
        self.viewGroupPlot_2.setCurrentText(_translate("MainWindow", "   View Group plot"))
        self.viewGroupPlot_2.setItemText(0, _translate("MainWindow", "   View Group plot"))
        self.machineLearningcomboBox.setCurrentText(_translate("MainWindow", "  Select Machine Learning"))
        self.machineLearningcomboBox.setItemText(0, _translate("MainWindow", "  Select Machine Learning"))
        self.machineLearningcomboBox.setItemText(1, _translate("MainWindow", "SVC- Support Vector Machine"))
        self.machineLearningcomboBox.setItemText(2, _translate("MainWindow", "Decision Tree Model"))
        self.machineLearningcomboBox.setItemText(3, _translate("MainWindow", "AdaBoost Model"))
        self.machineLearningcomboBox.setItemText(4, _translate("MainWindow", "Random Forest"))
        self.machineLearningcomboBox.setItemText(5, _translate("MainWindow", "XGBClassifier"))
        self.machinelearningLabel.setText(_translate("MainWindow", "          MACHINE LEARNING        "))
import images icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
